# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider :vm do |v|
  v.memory = 512
  v.cpus = 2
  v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.define "control" do |control|
    control.vm.hostname = "control"
    control.vm.synced_folder "playbooks-ansible/", "/home/ansible/ansible",
      create: true, id: "playbooks-ansible",
      owner: "ansible", group: "ansible"
    control.vm.network :private_network, ip: "192.168.8.110"
    control.vm.provision "shell", inline: <<-SHELL
      sudo yum install epel-release -y
      sudo yum install -y ansible
      sudo yum install -y vim
    SHELL
  end

  config.vm.define "web" do |web|
    web.vm.hostname = "node1"
    web.vm.network :private_network, ip: "192.168.8.120"
  end
 
  config.vm.define "db" do |db|
    db.vm.hostname = "node2"
    db.vm.network :private_network, ip: "192.168.8.130"
  end
end
  