global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node1'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.8.120:9100']
  - job_name: 'node2'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.8.130:9100']