- name: Install node_exporter 
  hosts: node1, node2
  become: yes
  become_user: root

  tasks:
    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /bin/false
        system: yes

    - name: Install prerequisites
      yum:
        name: epel-release
        state: present

    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz"
        dest: /opt/node_exporter-0.18.1.linux-amd64.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /opt/node_exporter-0.18.1.linux-amd64.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Copy Node Exporter binary
      copy:
        src: /opt/node_exporter-0.18.1.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        owner: node_exporter
        group: node_exporter
        mode: 0755
        remote_src: yes

    - name: Create Node Exporter service
      copy:
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/node_exporter.service

    - name: Start Node Exporter
      systemd:
        name: node_exporter
        state: started
        enabled: yes



#    - name: Delete file at /opt/
#      file:
#        path: /opt/
#        state: absent